'use strict';
const cards=[
{p:'You greet an older person in the morning.',y:'Ẹ káàárọ̀',e:'Good morning.',h:'Ẹ signals respect. Practise with a parent, grandparent or teacher.'},
{p:'You greet an older person in the afternoon.',y:'Ẹ káàsán',e:'Good afternoon.',h:'Notice the afternoon greeting changes, while Ẹ stays.'},
{p:'You greet an older person in the evening.',y:'Ẹ káalẹ́',e:'Good evening.',h:'This is an evening greeting, rather than a bedtime farewell.'},
{p:'An older relative arrives. You welcome them.',y:'Ẹ káàbọ̀',e:'Welcome.',h:'Use this to welcome someone arriving, not as a reply to “thank you”.'},
{p:'An older person helps you. You thank them.',y:'Ẹ ṣé',e:'Thank you.',h:'Use the respectful form when thanking an older person.'},
{p:'You ask a friend how they are.',y:'Báwo ni?',e:'How are you? / How are things?',h:'This card is a friendly check-in. Respectful forms vary with the person addressed.'},
{p:'Someone asks how you are. You are fine.',y:'Dáadáa ni',e:'I am fine.',h:'Take turns asking and answering.'},
{p:'You are leaving. You say goodbye.',y:'Ó dàbọ̀',e:'Goodbye.',h:'Try ending your short exchange with this farewell.'}
];
const sessions=[['Morning & respect','Practise card 1. Talk about whom you greet respectfully. Try the greeting without looking.'],['Afternoon & evening','Practise cards 2–3. Your partner names a time of day; choose the greeting.'],['A welcome & a thank-you','Practise cards 4–5. Act out a visitor arriving and someone helping you.'],['A friendly check-in','Practise cards 6–7. Take turns asking how things are and replying.'],['Bring it into real life','Review all eight cards. Greet someone, exchange a check-in and say goodbye without the screen. Ask a fluent speaker for feedback.']];
const key='obanimi-yoruba-together-v1';let state={marks:{},sessions:[]};try{const s=JSON.parse(localStorage.getItem(key));if(s&&typeof s.marks==='object'&&Array.isArray(s.sessions))state=s}catch{}let index=0,visible=false;const $=id=>document.getElementById(id);function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{$('progress').textContent='Browser storage is unavailable; progress will not be saved.'}}function set(){return cards.map((c,i)=>i).filter(i=>$('filter').value==='all'||state.marks[i]==='again')}
function render(){const ids=set();index=Math.min(index,Math.max(0,ids.length-1));visible=false;$('card').setAttribute('aria-expanded','false');$('answer').hidden=true;$('prompt').hidden=false;$('revealLabel').textContent='Tap to reveal ↗';$('cardLabel').textContent='Picture the moment';$('position').textContent=ids.length?`CARD ${index+1} OF ${ids.length}`:'No cards marked for extra practice';$('status').textContent=ids.length?(state.marks[ids[index]]==='known'?'Remembered':state.marks[ids[index]]==='again'?'Practise again':'New greeting'):'';$('prompt').textContent=ids.length?cards[ids[index]].p:'Choose “All greetings” to keep practising.';for(const id of ['prev','next','again','known','card'])$(id).disabled=!ids.length;if(ids.length){const c=cards[ids[index]];$('phrase').textContent=c.y;$('meaning').textContent=c.e;$('hint').textContent=c.h}$('progress').textContent=`${Object.values(state.marks).filter(m=>m==='known').length} of 8 marked remembered · ${state.sessions.length} of 5 sessions completed.`}
$('card').onclick=()=>{visible=!visible;$('card').setAttribute('aria-expanded',String(visible));$('answer').hidden=!visible;$('prompt').hidden=visible;$('cardLabel').textContent=visible?'Say it together':'Picture the moment';$('revealLabel').textContent=visible?'Tap to see the situation ↗':'Tap to reveal ↗'};for(const [id,step]of [['prev',-1],['next',1]])$(id).onclick=()=>{const n=set().length;index=(index+step+n)%n;render()};for(const [id,mark]of [['again','again'],['known','known']])$(id).onclick=()=>{state.marks[set()[index]]=mark;save();render()};$('filter').onchange=()=>{index=0;render()};
sessions.forEach(([title,body],i)=>{const d=document.createElement('div');d.className='session';const n=document.createElement('span');n.className='eyebrow';n.textContent=`Session 0${i+1}`;const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body;const label=document.createElement('label');const check=document.createElement('input');check.type='checkbox';check.checked=state.sessions.includes(i);check.onchange=()=>{state.sessions=check.checked?[...new Set([...state.sessions,i])]:state.sessions.filter(s=>s!==i);save();render()};label.append(check,' We practised this together');d.append(n,h,p,label);$('sessionList').append(d)});
let q=0,score=0;const questions=[0,1,3,4,6,7];function quiz(){const box=$('quiz');box.replaceChildren();$('quizFeedback').textContent='';$('quizNext').hidden=true;if(q===questions.length){const h=document.createElement('h3');h.textContent=`You matched ${score} of ${questions.length} situations.`;const p=document.createElement('p');p.textContent='Now practise with a person: greet them, ask how they are, respond and say goodbye. A quiz result does not assess pronunciation.';const b=document.createElement('button');b.className='primary';b.textContent='Try the practice again';b.onclick=()=>{q=0;score=0;quiz()};box.append(h,p,b);return}const correct=questions[q];const h=document.createElement('h3');h.textContent=`${q+1} / ${questions.length} · ${cards[correct].p}`;const options=document.createElement('div');options.className='options';const choices=[correct,(correct+2)%8,(correct+5)%8].sort((a,b)=>((a+q*3)%8)-((b+q*3)%8));choices.forEach(i=>{const b=document.createElement('button');b.lang='yo';b.textContent=cards[i].y;b.onclick=()=>{for(const child of options.children)child.disabled=true;b.classList.add('chosen');if(i===correct)score++;$('quizFeedback').textContent=(i===correct?'That fits. ':'Keep practising. ')+cards[correct].y+' — '+cards[correct].e;$('quizNext').hidden=false;$('quizNext').textContent=q===questions.length-1?'See your result →':'Next question →'};options.append(b)});box.append(h,options)}$('quizNext').onclick=()=>{q++;quiz()};
const title=document.createElement('h1');title.className='print-title';title.style.fontSize='28px';title.textContent='Yorùbá Together · Everyday greetings';$('printCards').append(title);cards.forEach(c=>{const d=document.createElement('div');d.className='print-card';const p=document.createElement('p');p.textContent=c.p;const h=document.createElement('h2');h.lang='yo';h.textContent=c.y;const e=document.createElement('p');e.textContent=c.e+' '+c.h;d.append(p,h,e);$('printCards').append(d)});const note=document.createElement('p');note.className='print-title';note.textContent='ObanimiStudio · Free pilot. Practise with a fluent speaker. Source: Yorùbá Yé Mi, Chapter 1, University of Texas at Austin. obanimistudio-star.github.io/obanimistudio-website/yoruba-together/';$('printCards').append(note);$('print').onclick=()=>window.print();$('reset').onclick=()=>{if(confirm('Reset your saved recall marks and session checklist?')){state={marks:{},sessions:[]};save();document.querySelectorAll('.session input').forEach(c=>c.checked=false);index=0;q=0;score=0;quiz();render()}};render();quiz();
