(function(){
"use strict";
const questions=window.YORUBA_QUESTIONS||[];
const categories={Language:["À","Words, greetings and tone marks"],Proverbs:["◌","Wisdom hidden in Yoruba sayings"],Culture:["✦","Customs, character and traditions"],History:["⌛","People, origins and great events"],Places:["⌖","States, capitals and landmarks"],Literature:["▤","Writers, books and storytelling"],General:["◆","Nigeria, numbers and general knowledge"]};
const $=id=>document.getElementById(id),screens=[$("homeScreen"),$("quizScreen"),$("resultScreen")];let game,timer,deferredInstall,soundOn=localStorage.getItem("yorubaSound")!=="off";
function getStats(){try{return JSON.parse(localStorage.getItem("yorubaStats"))||{}}catch(_){return{}}}function saveStats(value){localStorage.setItem("yorubaStats",JSON.stringify(value))}function updateStats(){const s=getStats();$("bestScore").textContent=s.bestScore||0;$("playedCount").textContent=s.played||0;$("streakCount").textContent=s.bestStreak||0}
function show(screen){screens.forEach(item=>item.classList.toggle("active",item===screen));scrollTo({top:0,behavior:"smooth"})}function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function tone(correct){if(!soundOn||!(window.AudioContext||window.webkitAudioContext))return;const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=correct?650:190;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+.25);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.26)}
function renderCategories(){$("categoryGrid").innerHTML=Object.entries(categories).map(([name,[icon,text]])=>`<button class="category-card" type="button" data-category="${name}" data-count="${questions.filter(q=>q.category===name).length} questions"><span class="category-icon">${icon}</span><h3>${name}</h3><p>${text}</p></button>`).join("");document.querySelectorAll(".category-card").forEach(button=>button.addEventListener("click",()=>start(button.dataset.category,10)))}
function start(category,amount){const pool=category?questions.filter(q=>q.category===category):questions;game={questions:shuffle(pool).slice(0,Math.min(amount,pool.length)),category:category||"Mixed challenge",index:0,score:0,streak:0,bestStreak:0,correct:0,answered:false,seconds:20,used:{fifty:false,time:false,skip:false}};$("questionTotal").textContent=game.questions.length;$("categoryLabel").textContent=game.category;$("scoreValue").textContent=0;[$("fiftyButton"),$("timeButton"),$("skipButton")].forEach(b=>b.disabled=false);show($("quizScreen"));renderQuestion()}
function renderQuestion(){clearInterval(timer);const q=game.questions[game.index];game.answered=false;game.seconds=20;$("questionNumber").textContent=game.index+1;$("progressBar").style.width=`${(game.index+1)/game.questions.length*100}%`;$("difficultyLabel").textContent=q.difficulty;$("questionText").textContent=q.question;$("yorubaHint").textContent=q.hint||"";$("feedbackPanel").hidden=true;$("answers").innerHTML=q.answers.map((answer,index)=>`<button class="answer-button" type="button" data-index="${index}"><span class="answer-letter">${String.fromCharCode(65+index)}</span><span>${answer}</span></button>`).join("");document.querySelectorAll(".answer-button").forEach(button=>button.addEventListener("click",()=>answer(Number(button.dataset.index))));tick();timer=setInterval(()=>{game.seconds--;tick();if(game.seconds<=0)answer(-1)},1000)}
function tick(){$("timerValue").textContent=game.seconds;$("timerValue").parentElement.style.background=game.seconds<=5?"#b53a2d":"var(--green)"}
function answer(selected){if(!game||game.answered)return;game.answered=true;clearInterval(timer);const q=game.questions[game.index],correct=selected===q.correct;document.querySelectorAll(".answer-button").forEach((button,index)=>{button.disabled=true;if(index===q.correct)button.classList.add("correct");if(index===selected&&!correct)button.classList.add("wrong")});if(correct){game.score+=100+game.seconds*5+game.streak*15;game.correct++;game.streak++;game.bestStreak=Math.max(game.bestStreak,game.streak);$("feedbackIcon").textContent="✓";$("feedbackTitle").textContent="Ó pé! Correct"}else{game.streak=0;$("feedbackIcon").textContent="×";$("feedbackTitle").textContent=selected<0?"Àkókò ti tán — Time's up":"Kò pé — Not quite"}tone(correct);$("scoreValue").textContent=game.score;$("feedbackText").textContent=q.explanation;$("feedbackPanel").hidden=false;$("nextButton").textContent=game.index===game.questions.length-1?"See results →":"Next question →"}
function next(){if(!game.answered)return;if(game.index<game.questions.length-1){game.index++;renderQuestion()}else finish()}
function finish(){clearInterval(timer);const total=game.questions.length,accuracy=Math.round(game.correct/total*100),s=getStats();saveStats({played:(s.played||0)+1,bestScore:Math.max(s.bestScore||0,game.score),bestStreak:Math.max(s.bestStreak||0,game.bestStreak)});updateStats();$("finalScore").textContent=game.score;$("finalTotal").textContent="points";$("correctCount").textContent=`${game.correct}/${total}`;$("accuracyValue").textContent=`${accuracy}%`;$("resultStreak").textContent=game.bestStreak;$("scoreRing").style.background=`conic-gradient(var(--green) 0 ${accuracy*3.6}deg,var(--gold) ${accuracy*3.6}deg ${Math.min(360,accuracy*3.6+25)}deg,#e9eee9 0deg)`;if(accuracy>=80){$("resultEmblem").textContent="🏆";$("resultTitle").textContent="Àgbàyanu!";$("resultMessage").textContent="Outstanding work — you truly know your Yoruba."}else if(accuracy>=50){$("resultEmblem").textContent="🌟";$("resultTitle").textContent="O ṣe dáadáa!";$("resultMessage").textContent="Well done. A little more practice will take you even higher."}else{$("resultEmblem").textContent="🌱";$("resultTitle").textContent="Máa tẹ̀síwájú!";$("resultMessage").textContent="Keep going — every question is helping your knowledge grow."}show($("resultScreen"))}
$("quickPlayButton").addEventListener("click",()=>start(null,10));$("dailyButton").addEventListener("click",()=>start(null,5));$("categoriesButton").addEventListener("click",()=>$("categorySection").scrollIntoView({behavior:"smooth"}));$("nextButton").addEventListener("click",next);$("playAgainButton").addEventListener("click",()=>start(game.category==="Mixed challenge"?null:game.category,game.questions.length));$("homeButton").addEventListener("click",()=>show($("homeScreen")));$("quitButton").addEventListener("click",()=>{clearInterval(timer);if(confirm("Leave this challenge and return home?"))show($("homeScreen"));else timer=setInterval(()=>{game.seconds--;tick();if(game.seconds<=0)answer(-1)},1000)});
$("soundButton").addEventListener("click",()=>{soundOn=!soundOn;localStorage.setItem("yorubaSound",soundOn?"on":"off");$("soundButton").textContent=soundOn?"♪":"×"});
$("fiftyButton").addEventListener("click",()=>{if(game.used.fifty||game.answered)return;game.used.fifty=true;$("fiftyButton").disabled=true;const q=game.questions[game.index];shuffle([0,1,2,3].filter(i=>i!==q.correct)).slice(0,2).forEach(i=>document.querySelector(`.answer-button[data-index="${i}"]`).classList.add("removed"))});$("timeButton").addEventListener("click",()=>{if(game.used.time||game.answered)return;game.used.time=true;game.seconds+=10;tick();$("timeButton").disabled=true});$("skipButton").addEventListener("click",()=>{if(game.used.skip||game.answered)return;game.used.skip=true;$("skipButton").disabled=true;game.answered=true;if(game.index<game.questions.length-1){game.index++;renderQuestion()}else finish()});
addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstall=event;$("installButton").hidden=false});$("installButton").addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installButton").hidden=true});addEventListener("appinstalled",()=>$("installButton").hidden=true);function status(){$("onlineStatus").textContent=navigator.onLine?"● Online":"● Offline mode"}addEventListener("online",status);addEventListener("offline",status);if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));renderCategories();updateStats();status();
})();
