(function(){
"use strict";
const questions=window.YORUBA_QUESTIONS||[];
const categoryCards=[
  {name:"Gbogbo Ẹ̀kọ́",icon:"✦",text:"Gbogbo ìmọ̀ papọ̀",filter:null},
  {name:"Èdè Yorùbá",icon:"À",text:"Ọ̀rọ̀, ìkíni àti àmì ohùn",filter:"Language"},
  {name:"Òwe Yorùbá",icon:"◌",text:"Ọgbọ́n inú òwe Yorùbá",filter:"Proverbs"},
  {name:"Ìtàn Yorùbá",icon:"⌛",text:"Ìpilẹ̀ àti àwọn ẹni pàtàkì",filter:"YorubaHistory"},
  {name:"Àwọn Ọba Yorùbá",icon:"♛",text:"Àwọn ìlú, oyè àti ọba",filter:"YorubaKings"},
  {name:"Ìṣirò",icon:"Σ",text:"Ìṣirò àti ìbéèrè ọgbọ́n",filter:"Math"},
  {name:"Ẹ̀kọ́ Iṣẹ́ Àgbẹ̀",icon:"♣",text:"Ohun ọ̀gbìn, ẹranko àti ilẹ̀",filter:"Agriculture"},
  {name:"Nàìjíríà àti Ilé Ẹ̀kọ́",icon:"▣",text:"Ìpínlẹ̀, olú-ìlú àti ilé-ẹ̀kọ́",filter:"NigeriaEducation"},
  {name:"Ìwé àti Òǹkọ̀wé",icon:"▤",text:"Lítíréṣọ̀ àti àwọn òǹkọ̀wé",filter:"Literature"},
  {name:"Eré Ìdárayá",icon:"⚽",text:"Bọ́ọ̀lù, eré àti àwọn agbábọ́ọ̀lù",filter:"Sports"},
  {name:"Ìmọ̀ Sáyẹ́ǹsì",icon:"⚗",text:"Ara, ayé àti ìmọ̀ ẹ̀rọ",filter:"Science"},
  {name:"Àwọn Olùdásílẹ̀",icon:"✦",text:"Àwọn olùpilẹ̀ṣẹ̀ àti iṣẹ́ wọn",filter:"Inventors"},
  {name:"Ìmọ̀ Ayé",icon:"🌍",text:"Orílẹ̀-èdè, olú-ìlú àti àgbáyé",filter:"WorldKnowledge"}
];
const $=id=>document.getElementById(id);
const screens=[$("homeScreen"),$("quizScreen"),$("resultScreen")];
const ladder=[100,200,300,500,1000,2000,4000,8000,16000,32000];
let game,timer,deferredInstall,selectedDifficulty="All",language="YO";
let soundOn=localStorage.getItem("yorubaSound")!=="off",musicOn=localStorage.getItem("yorubaMusic")!=="off",audioContext,musicTimer;
const certificateMark=new Image();certificateMark.src="icons/icon-512.png";
function getStats(){try{return JSON.parse(localStorage.getItem("yorubaStats"))||{}}catch(_){return{}}}
function saveStats(value){localStorage.setItem("yorubaStats",JSON.stringify(value))}
function updateStats(){const s=getStats();$("bestScore").textContent=s.bestScore||0;$("playedCount").textContent=s.played||0;$("streakCount").textContent=s.bestStreak||0}
function show(screen){screens.forEach(item=>item.classList.toggle("active",item===screen));scrollTo({top:0,behavior:"smooth"})}
function shuffle(items){const copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function filteredPool(filter){let pool=filter?questions.filter(q=>filter.split("|").includes(q.category)):questions;if(selectedDifficulty!=="All")pool=pool.filter(q=>q.difficulty===selectedDifficulty);return pool.length?pool:(filter?questions.filter(q=>filter.split("|").includes(q.category)):questions)}
function selectFresh(pool,amount){let seen=[];try{seen=JSON.parse(localStorage.getItem("yorubaSeenQuestions"))||[]}catch(_){seen=[]}const seenSet=new Set(seen),fresh=shuffle(pool.filter(q=>!seenSet.has(q.id))),older=shuffle(pool.filter(q=>seenSet.has(q.id))),chosen=[...fresh,...older].slice(0,Math.min(amount,pool.length));const updated=[...seen,...chosen.map(q=>q.id)].slice(-Math.min(900,questions.length));localStorage.setItem("yorubaSeenQuestions",JSON.stringify([...new Set(updated)]));return chosen}
function audio(){if(!audioContext){const C=window.AudioContext||window.webkitAudioContext;if(C)audioContext=new C()}if(audioContext?.state==="suspended")audioContext.resume();return audioContext}
function note(frequency,duration=.22,volume=.045,delay=0){if(!soundOn)return;const c=audio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),start=c.currentTime+delay;o.type="sine";o.frequency.value=frequency;g.gain.setValueAtTime(volume,start);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g).connect(c.destination);o.start(start);o.stop(start+duration)}
function feedbackSound(correct){if(correct){note(523,.17,.07);note(659,.18,.07,.13);note(784,.3,.075,.27)}else{note(180,.3,.07);note(135,.34,.055,.16)}}
function startMusic(){stopMusic();if(!soundOn||!musicOn)return;const melody=()=>{[261,329,392,523].forEach((n,i)=>note(n,.48,.018,i*.42))};melody();musicTimer=setInterval(melody,2200)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function renderCategories(){$("categoryGrid").innerHTML=categoryCards.map(card=>{const count=card.filter?questions.filter(q=>card.filter.split("|").includes(q.category)).length:questions.length;return `<button class="category-card" type="button" data-filter="${card.filter||""}" data-name="${card.name}" data-count="${count} questions"><span class="category-icon">${card.icon}</span><h3>${card.name}</h3><p>${card.text}</p></button>`}).join("");document.querySelectorAll(".category-card").forEach(button=>button.addEventListener("click",()=>start(button.dataset.filter||null,10,button.dataset.name)))}
function renderLadder(){$("moneyLadder").innerHTML=ladder.map((value,index)=>`<li class="${index===game.index?"current":""} ${[4,9].includes(index)?"safe":""}"><span>${index+1}${[4,9].includes(index)?" ◆":""}</span><b>${value.toLocaleString()} àmì</b></li>`).join("")}
function start(filter,amount,label){const pool=filteredPool(filter);game={questions:selectFresh(pool,amount),filter,category:label||"Gbogbo Ẹ̀kọ́",index:0,score:0,streak:0,bestStreak:0,correct:0,answered:false,seconds:25,used:{fifty:false,audience:false,time:false,skip:false}};$("questionTotal").textContent=game.questions.length;$("categoryLabel").textContent=game.category;$("scoreValue").textContent=0;[$("fiftyButton"),$("audienceButton"),$("timeButton"),$("skipButton")].forEach(b=>b.disabled=false);show($("quizScreen"));startMusic();renderQuestion()}
function renderQuestion(){clearInterval(timer);const q=game.questions[game.index];game.answered=false;game.seconds=25;const ordered=shuffle(q.answers.map((answer,index)=>({answer,correct:index===q.correct})));game.answerOrder=ordered;game.correctIndex=ordered.findIndex(item=>item.correct);$("questionNumber").textContent=game.index+1;$("progressBar").style.width=`${(game.index+1)/game.questions.length*100}%`;$("difficultyLabel").textContent={Easy:"Àwọn Ọmọdé",Medium:"Ìdílé",Hard:"Ọ̀mọ̀wé"}[q.difficulty]||q.difficulty;$("questionText").textContent=q.question;$("yorubaHint").textContent=q.hint||"";$("feedbackPanel").hidden=true;$("audiencePoll").hidden=true;$("answers").innerHTML=ordered.map((item,index)=>`<button class="answer-button" type="button" data-index="${index}"><span class="answer-letter">${String.fromCharCode(65+index)}</span><span>${item.answer}</span></button>`).join("");document.querySelectorAll(".answer-button").forEach(button=>button.addEventListener("click",()=>answerQuestion(Number(button.dataset.index))));renderLadder();tick();timer=setInterval(()=>{game.seconds--;tick();if(game.seconds<=0)answerQuestion(-1)},1000)}
function tick(){$("timerValue").textContent=game.seconds;$("timerValue").parentElement.style.background=game.seconds<=5?"linear-gradient(145deg,#d61d50,#ff662e)":"linear-gradient(145deg,var(--blue),var(--purple))"}
function answerQuestion(selected){if(!game||game.answered)return;game.answered=true;clearInterval(timer);const q=game.questions[game.index],timedOut=selected<0,correct=selected===game.correctIndex;document.querySelectorAll(".answer-button").forEach((button,index)=>{button.disabled=true;if(index===game.correctIndex)button.classList.add(timedOut?"revealed":"correct");if(index===selected&&!correct)button.classList.add("wrong")});if(correct){game.score=ladder[Math.min(game.index,ladder.length-1)]+game.seconds*5;game.correct++;game.streak++;game.bestStreak=Math.max(game.bestStreak,game.streak);$("feedbackIcon").textContent="✓";$("feedbackTitle").textContent="Ó pé! Correct"}else{game.streak=0;$("feedbackIcon").textContent=timedOut?"⌛":"×";$("feedbackTitle").textContent=timedOut?"Àkókò ti tán — Correct answer shown":"Kò pé — Not quite"}feedbackSound(correct);$("scoreValue").textContent=game.score;$("feedbackText").textContent=q.explanation;$("feedbackPanel").hidden=false;$("nextButton").textContent=game.index===game.questions.length-1?"Wo èsì →":"Ìbéèrè tó kàn →"}
function next(){if(!game.answered)return;if(game.index<game.questions.length-1){game.index++;renderQuestion()}else finish()}
function finish(){clearInterval(timer);stopMusic();const total=game.questions.length,accuracy=Math.round(game.correct/total*100),s=getStats();saveStats({played:(s.played||0)+1,bestScore:Math.max(s.bestScore||0,game.score),bestStreak:Math.max(s.bestStreak||0,game.bestStreak)});updateStats();$("finalScore").textContent=game.score;$("correctCount").textContent=`${game.correct}/${total}`;$("accuracyValue").textContent=`${accuracy}%`;$("resultStreak").textContent=game.bestStreak;$("scoreRing").style.background=`conic-gradient(var(--aqua) 0 ${accuracy*3.6}deg,var(--purple) ${accuracy*3.6}deg ${Math.min(360,accuracy*3.6+24)}deg,rgba(255,255,255,.08) 0deg)`;if(accuracy>=80){$("resultEmblem").textContent="🏆";$("resultTitle").textContent="Àgbàyanu!";$("resultMessage").textContent="O ṣe dáadáa gan-an — ọgbọ́n Yorùbá rẹ ga."}else if(accuracy>=50){$("resultEmblem").textContent="🌟";$("resultTitle").textContent="O ṣe dáadáa!";$("resultMessage").textContent="Ìdánwò rẹ dára. Máa tẹ̀síwájú."}else{$("resultEmblem").textContent="🌱";$("resultTitle").textContent="Máa tẹ̀síwájú!";$("resultMessage").textContent="Gbogbo ìbéèrè ń mú kí ìmọ̀ rẹ pọ̀ sí i."}$("certificateError").textContent="";show($("resultScreen"));[523,659,784,1047].forEach((n,i)=>note(n,.4,.055,i*.18))}
async function downloadCertificate(){const name=$("certificateName").value.trim();if(!name){$("certificateError").textContent="Jọ̀wọ́ tẹ orúkọ rẹ.";return}if(!certificateMark.complete)await certificateMark.decode();const canvas=$("certificateCanvas"),ctx=canvas.getContext("2d"),gradient=ctx.createLinearGradient(0,0,1600,1130);gradient.addColorStop(0,"#fffdf3");gradient.addColorStop(1,"#eafcff");ctx.fillStyle=gradient;ctx.fillRect(0,0,1600,1130);ctx.strokeStyle="#0b8c91";ctx.lineWidth=18;ctx.strokeRect(38,38,1524,1054);ctx.strokeStyle="#d6a217";ctx.lineWidth=5;ctx.strokeRect(64,64,1472,1002);ctx.textAlign="center";ctx.fillStyle="#0b8c91";ctx.font="800 27px Manrope";ctx.fillText("ISSUED BY · OBANIMISTUDIO",800,135);ctx.fillStyle="#12223f";ctx.font="800 76px Georgia";ctx.fillText("Ẹ̀RÍ ÀṢEYỌRÍ",800,255);ctx.font="600 31px Manrope";ctx.fillStyle="#6c6b66";ctx.fillText("CERTIFICATE OF ACHIEVEMENT",800,310);ctx.font="400 30px Manrope";ctx.fillText("A fi ẹ̀rí yìí fún",800,415);ctx.fillStyle="#3d2ab8";ctx.font="800 68px Georgia";ctx.fillText(name,800,525);ctx.strokeStyle="#d6a217";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(330,560);ctx.lineTo(1270,560);ctx.stroke();ctx.fillStyle="#12223f";ctx.font="600 30px Manrope";ctx.fillText("fún píparí ìdánwò “Ṣé o mọ èdè Yorùbá?”",800,630);ctx.fillStyle="#0b8c91";ctx.font="800 31px Manrope";ctx.fillText(`${game.correct}/${game.questions.length} correct  •  ${game.score.toLocaleString()} àmì`,800,700);ctx.save();ctx.shadowColor="rgba(30,53,98,.28)";ctx.shadowBlur=28;ctx.drawImage(certificateMark,685,735,230,230);ctx.restore();ctx.fillStyle="#6c6b66";ctx.font="400 23px Manrope";ctx.fillText(new Date().toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"}),800,1030);const link=document.createElement("a");link.download=`Se-o-mo-ede-Yoruba-${name.replace(/[^a-z0-9]+/gi,"-")}.png`;link.href=canvas.toDataURL("image/png");link.click()}
$("quickPlayButton").addEventListener("click",()=>start(null,10,"Gbogbo Ẹ̀kọ́"));$("dailyButton").addEventListener("click",()=>start(null,5,"Ìdánwò ọjọ́"));$("categoriesButton").addEventListener("click",()=>$("categorySection").scrollIntoView({behavior:"smooth"}));$("nextButton").addEventListener("click",next);$("playAgainButton").addEventListener("click",()=>start(game.filter,game.questions.length,game.category));$("homeButton").addEventListener("click",()=>{stopMusic();show($("homeScreen"))});$("quitButton").addEventListener("click",()=>{clearInterval(timer);stopMusic();if(confirm("Ṣé o fẹ́ padà sí ilé?"))show($("homeScreen"));else{startMusic();timer=setInterval(()=>{game.seconds--;tick();if(game.seconds<=0)answerQuestion(-1)},1000)}});
document.querySelectorAll(".difficulty").forEach(button=>button.addEventListener("click",()=>{selectedDifficulty=button.dataset.difficulty;document.querySelectorAll(".difficulty").forEach(b=>b.classList.toggle("active",b===button))}));
$("soundButton").addEventListener("click",()=>{soundOn=!soundOn;musicOn=soundOn;localStorage.setItem("yorubaSound",soundOn?"on":"off");localStorage.setItem("yorubaMusic",musicOn?"on":"off");$("soundButton").textContent=soundOn?"♪":"×";soundOn?startMusic():stopMusic()});
$("themeButton").addEventListener("click",()=>{const themes=["dark","cool","light"],current=document.body.dataset.theme||"dark";document.body.dataset.theme=themes[(themes.indexOf(current)+1)%themes.length]});
$("languageButton").addEventListener("click",()=>{language=language==="YO"?"EN":"YO";$("languageButton").textContent=language==="YO"?"EN":"YO";$("quickPlayButton").firstChild.textContent=language==="YO"?"BẸ̀RẸ̀ ÌDÁNWÒ ":"START QUIZ ";$("categoriesButton").textContent=language==="YO"?"YAN Ẹ̀KA Ẹ̀KỌ́":"CHOOSE CATEGORY"});
$("fiftyButton").addEventListener("click",()=>{if(game.used.fifty||game.answered)return;game.used.fifty=true;$("fiftyButton").disabled=true;shuffle([0,1,2,3].filter(i=>i!==game.correctIndex)).slice(0,2).forEach(i=>document.querySelector(`.answer-button[data-index="${i}"]`).classList.add("removed"))});
$("audienceButton").addEventListener("click",()=>{if(game.used.audience||game.answered)return;game.used.audience=true;$("audienceButton").disabled=true;const winning=58+Math.floor(Math.random()*23),remaining=100-winning,cuts=[Math.floor(remaining*.5),Math.floor(remaining*.3)];const values=[0,0,0,0];values[game.correctIndex]=winning;let others=[0,1,2,3].filter(i=>i!==game.correctIndex);values[others[0]]=cuts[0];values[others[1]]=cuts[1];values[others[2]]=remaining-cuts[0]-cuts[1];$("audiencePoll").innerHTML=values.map((value,index)=>`<div><span style="height:${value}%"></span><b>${String.fromCharCode(65+index)}</b><small>${value}%</small></div>`).join("");$("audiencePoll").hidden=false});
$("timeButton").addEventListener("click",()=>{if(game.used.time||game.answered)return;game.used.time=true;game.seconds+=10;tick();$("timeButton").disabled=true});$("skipButton").addEventListener("click",()=>{if(game.used.skip||game.answered)return;game.used.skip=true;$("skipButton").disabled=true;game.answered=true;if(game.index<game.questions.length-1){game.index++;renderQuestion()}else finish()});$("certificateButton").addEventListener("click",downloadCertificate);
addEventListener("beforeinstallprompt",event=>{event.preventDefault();deferredInstall=event;$("installButton").hidden=false});$("installButton").addEventListener("click",async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installButton").hidden=true});addEventListener("appinstalled",()=>$("installButton").hidden=true);function status(){$("onlineStatus").textContent=navigator.onLine?"● Online":"● Offline mode"}addEventListener("online",status);addEventListener("offline",status);if("serviceWorker" in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));$("bankSummary").textContent=`12 Ẹ̀KA Ẹ̀KỌ́ · 4 ÌRÀNLỌ́WỌ́ · 2 ÈDÈ · ${questions.length.toLocaleString()} ÌBÉÈRÈ`;renderCategories();updateStats();status();
})();
