(function(){
"use strict";
const bank=[],levels=["Easy","Medium","Hard"];
const datasets={
Language:`A kú àárọ̀|Ìkíni òwúrọ̀;A kú ọ̀sán|Ìkíni ọ̀sán;A kú ìrọ̀lẹ́|Ìkíni ìrọ̀lẹ́;Ó dàárọ̀|Ìkíni kí a tó sùn;Ẹ káàbọ̀|Ìkíni àbọ̀;Ẹ kú iṣẹ́|Ìkíni fún ẹni tó ń ṣiṣẹ́;Mo dúpẹ́|Thank you;Jọ̀wọ́|Please;Má bínú|Sorry;Bẹ́ẹ̀ ni|Yes;Rárá|No;Omi|Water;Oúnjẹ|Food;Ilé|House;Ọjà|Market;Ọ̀rẹ́|Friend;Ìwé|Book;Ilé-ẹ̀kọ́|School;Olùkọ́|Teacher;Akẹ́kọ̀ọ́|Student;Ọmọ|Child;Bàbá|Father;Ìyá|Mother;Àbúrò|Younger sibling;Ẹ̀gbọ́n|Older sibling;Orí|Head;Ojú|Eye;Etí|Ear;Imú|Nose;Ẹnu|Mouth;Ọwọ́|Hand;Ẹsẹ̀|Leg or foot;Àjà|Dog;Ológbò|Cat;Ẹyẹ|Bird;Ẹja|Fish;Màlúù|Cow;Ewúrẹ́|Goat;Adìẹ|Chicken;Pupa|Red;Dúdú|Black;Funfun|White;Àwọ̀ ewé|Green;Búlúù|Blue;Ọjọ́ Ajé|Monday;Ọjọ́ Ìṣẹ́gun|Tuesday;Ọjọ́rú|Wednesday;Ọjọ́bọ̀|Thursday;Ọjọ́ Ẹtì|Friday;Ọjọ́ Àbámẹ́ta|Saturday;Ọjọ́ Àìkú|Sunday`,
Proverbs:`Bí ọmọde bá ṣubú, a wo iwájú; bí àgbà bá ṣubú, a wo ẹ̀yìn|Àgbà ń kẹ́kọ̀ọ́ láti ohun tó ti ṣẹlẹ̀;Àìkú parí ìwà|Eni to wa laaye le tun iwa se;Ọ̀rọ̀ pẹ̀lẹ́ ló ń yọ obì lápò|Ọ̀rọ̀ rere ń mú àlàáfíà wá;Ọwọ́ kan kò gbérù dórí|Ìfọwọ́sowọ́pọ̀ ṣe pàtàkì;Àgbà kì í wà lọ́jà kí orí ọmọ tuntun wọ́|Àwọn àgbà ń dáàbò bo àwùjọ;Ilé la ti ń kọ́ ẹ̀ṣọ́ ròde|Ìwà rere bẹ̀rẹ̀ láti inú ilé;Ìwà l'ẹwà|Ìwà rere ni ẹwà tòótọ́;Sùúrù l'èrè|Ìfaradà máa ń mú èrè wá;A kì í fi ọwọ́ kan pàtẹ́wọ́|Eni kan ko le se gbogbo nkan nikan;Bí kò bá nídi, obìnrin kì í jẹ́ Kúmólú|Ohun gbogbo ní ìdí rẹ̀;Ọ̀nà kan ò wọ ọjà|Ọ̀pọ̀ ọ̀nà ló wà láti dé ibi àfojúsùn;Ẹni tí ó bá mọ̀wé, ó mọ̀ọ́ ṣe|Ìmọ̀ gbọdọ̀ bá ìṣe lọ;Omi l'ènìyàn|Ènìyàn nílò àwọn ẹlòmíràn;Ọgbọ́n ju agbára lọ|Ìmòye le ju lílo agbára lasan lọ;Tí a bá ń sunkún, a máa ríran|Ìṣòro kò gbọdọ̀ dá wa dúró láti ronú;Bí a bá rán ni níṣẹ́ ẹrú, a fi ti ọmọ jẹ|A gbọdọ̀ ṣe iṣẹ́ pẹ̀lú ọgbọ́n àti ìwà rere`,
YorubaHistory:`Ilé-Ifẹ̀|Orísun ọ̀làjú Yorùbá;Odùduwà|Baba ńlá tí ìtàn Yorùbá so mọ́ Ilé-Ifẹ̀;Ọ̀yọ́ Ilé|Olú ìjọba Ọ̀yọ́ àtijọ́;Ọ̀yọ́ Mèsì|Àgbàjọ àwọn olórí ìjọba Ọ̀yọ́;Baṣọ̀run|Olórí Ọ̀yọ́ Mèsì;Aare Ọ̀nà Kakanfò|Olórí ogun ilẹ̀ Ọ̀yọ́;Moremi Ajasoro|Akíkanjú obìnrin Ilé-Ifẹ̀;Lisabi Agbongbo-Akala|Akíkanjú tí ìtàn Ẹ̀gbá so mọ́ òmìnira;Sàngó|Alaafin Ọ̀yọ́ kan nínú ìtàn Yorùbá;Oranmiyan|Ọmọ Odùduwà tí ìtàn so mọ́ Ọ̀yọ́ àti Benin;Kírìjì|Ogun Yorùbá tó pẹ́ ní ọ̀rúndún kọkàndínlógún;Ìbàdàn|Ìlú tó di agbára ológun pàtàkì;Abeokuta|Ìlú pàtàkì àwọn Ẹ̀gbá;Ijebu-Ode|Ìlú pàtàkì àwọn Ìjẹ̀bú;Osogbo|Olú ìlú ìpínlẹ̀ Ọ̀ṣun;Akure|Olú ìlú ìpínlẹ̀ Ondo;Ado-Ekiti|Olú ìlú ìpínlẹ̀ Ekiti`,
YorubaKings:`Ooni|Oyẹ ọba Ilé-Ifẹ̀;Alaafin|Oyẹ ọba Ọ̀yọ́;Olubadan|Oyẹ ọba Ìbàdàn;Alake|Oyẹ ọba Ẹ̀gbá Aláké;Awujale|Oyẹ ọba Ìjẹ̀bú;Deji|Oyẹ ọba Akure;Ewi|Oyẹ ọba Ado-Ekiti;Soun|Oyẹ ọba Ogbomoso;Timi|Oyẹ ọba Ede;Ataoja|Oyẹ ọba Osogbo;Orangun|Oyẹ ọba Ila;Oluwo|Oyẹ ọba Iwo;Akarigbo|Oyẹ ọba Remo;Olowo|Oyẹ ọba Owo;Eleko|Oyẹ ọba Eko;Owa Obokun|Oyẹ ọba Ijesaland`,
Agriculture:`Àgbàdo|Maize;Iṣu|Yam;Ẹ̀wà|Beans;Irẹsì|Rice;Ẹ̀pà|Groundnut;Kókó|Cocoa;Èso ọ̀pẹ|Palm fruit;Rọ́bà|Rubber crop;Ẹ̀gẹ́|Cassava;Ọ̀gẹ̀dẹ̀|Banana or plantain;Tòmátì|Tomato;Àlùbọ́sà|Onion;Ata|Pepper;Ilá|Okra;Màlúù|Cattle;Ewúrẹ́|Goat;Àgùntàn|Sheep;Adìẹ|Poultry bird;Ẹlẹ́dẹ̀|Pig;Compost|Ajílẹ̀ láti ewé àti egbin jíjẹrà;Irrigation|Fífi omi bọ ilẹ̀ oko;Weeding|Yíyọ èpò kúrò ní oko;Harvesting|Kíkó èso oko;Planting|Gbígbìn irúgbìn;Pesticide|Ohun ìdènà kòkòrò oko;Barn|Ibi ìpamọ́ èso oko`,
NigeriaEducation:`Abuja|Olú ìlú Nàìjíríà;Lagos|Olú ìlú Nàìjíríà tẹ́lẹ̀;1 October 1960|Ọjọ́ òmìnira Nàìjíríà;Naira|Owó Nàìjíríà;Green and white|Àwọ̀ àsìá Nàìjíríà;36|Iye ìpínlẹ̀ Nàìjíríà;Federal Capital Territory|Agbègbè tí Abuja wà;River Niger|Ọ̀kan lára odò ńlá Nàìjíríà;River Benue|Odò tó darapọ̀ mọ́ Niger ní Lokoja;Lokoja|Ibi tí Niger àti Benue ti pàdé;University of Ibadan|Yunifásítì ìjọba àpapọ̀ ní Ibadan;Obafemi Awolowo University|Yunifásítì ní Ile-Ife;University of Lagos|Yunifásítì ní Akoka;University of Nigeria|Yunifásítì ní Nsukka;Ahmadu Bello University|Yunifásítì ní Zaria;University of Ilorin|Yunifásítì ní Ilorin;Yaba College of Technology|Polytechnic ní Yaba;Federal Polytechnic Ilaro|Polytechnic ní Ilaro;Lagos State|Ikeja;Oyo State|Ibadan;Ogun State|Abeokuta;Osun State|Osogbo;Ondo State|Akure;Ekiti State|Ado-Ekiti;Kwara State|Ilorin;Rivers State|Port Harcourt;Enugu State|Enugu;Anambra State|Awka;Plateau State|Jos;Borno State|Maiduguri;Cross River State|Calabar;Edo State|Benin City;Imo State|Owerri;JAMB|Àjọ tó ń ṣètò UTME;WAEC|West African Examinations Council;NECO|National Examinations Council`,
Literature:`D. O. Fagunwa|Òǹkọ̀wé Ògbójú Ọdẹ nínú Igbó Irúnmalẹ̀;Wole Soyinka|Nobel Prize in Literature ní 1986;Chinua Achebe|Òǹkọ̀wé Things Fall Apart;Cyprian Ekwensi|Òǹkọ̀wé Jagua Nana;Buchi Emecheta|Òǹkọ̀wé The Joys of Motherhood;Ben Okri|Òǹkọ̀wé The Famished Road;Flora Nwapa|Òǹkọ̀wé Efuru;Amos Tutuola|Òǹkọ̀wé The Palm-Wine Drinkard;Akinwumi Isola|Òǹkọ̀wé Oleku;Adebayo Faleti|Akéwì àti akọ̀ròyìn Yorùbá;Òwe|Proverb;Àlọ́|Folktale;Oríkì|Praise poetry;Ewì|Poetry;Eré onítàn|Drama;Ìtàn àròsọ|Fiction;Ìtàn ìgbésí ayé|Biography;Àkòrí|Theme;Àwọn ohun kikọ|Characters;Olùbánisọ̀rọ̀|Narrator`,
Sports:`11|Iye agbábọ́ọ̀lù ẹgbẹ́ kan lórí pápá;90 minutes|Àkókò bọ́ọ̀lù àgbà láìka àfikún;Goalkeeper|Ẹni tó ń ṣọ́ gọ́ọ̀lù;Referee|Adájọ́ eré;Penalty kick|Ìgbá láti àmì ìjìyà;Corner kick|Ìgbá láti igun pápá;Yellow card|Ìkìlọ̀ adájọ́;Red card|Ìyọkúrò nínú eré;Basketball|Eré tí a ń ju bọ́ọ̀lù sínú àwọ̀n gíga;Volleyball|Eré tí àwọ̀n wà láàárín ẹgbẹ́ méjì;Tennis|Eré racket lórí court;Table tennis|Eré racket lórí tábìlì;Athletics|Eré sísáré, fífò àti jíju;Marathon|Ere-ije gigun 42.195 km;Relay|Ere-ije tí a fi baton ránṣẹ́;Long jump|Fífo síwájú sínú iyanrìn;High jump|Fífo kọjá igi gíga;Swimming|Eré inú omi;Boxing|Eré ìjà pẹ̀lú ibọwọ́;Wrestling|Eré gídígbò;Super Eagles|Ẹgbẹ́ bọ́ọ̀lù ọkùnrin Nàìjíríà;Super Falcons|Ẹgbẹ́ bọ́ọ̀lù obìnrin Nàìjíríà;FIFA|Àjọ bọ́ọ̀lù àgbáyé;CAF|Àjọ bọ́ọ̀lù Áfíríkà;Hat-trick|Gọ́ọ̀lù mẹ́ta láti ọwọ́ agbábọ́ọ̀lù kan;Offside|Òfin ipò àìtọ́ ní bọ́ọ̀lù;Captain|Olórí ẹgbẹ́ eré;Coach|Olùkọ́ ẹgbẹ́ eré;Stadium|Ibi ńlá fún eré ìdárayá`,
Science:`Heart|Ẹ̀yà ara tó ń fa ẹ̀jẹ̀ ká;Lungs|Ẹ̀yà ara fún mímí;Brain|Ẹ̀yà tó ń darí ọ̀pọ̀ iṣẹ́ ara;Skeleton|Àkójọpọ̀ egungun ara;Skin|Ẹ̀yà ara tó bo gbogbo ara;Photosynthesis|Ọ̀nà tí ewéko fi ń ṣe oúnjẹ pẹ̀lú ìmọ́lẹ̀;Chlorophyll|Ohun aláwọ̀ ewé nínú ewé;Oxygen|Gaasi tí ènìyàn nílò fún mímí;Carbon dioxide|Gaasi tí ewéko ń lò;Water|H₂O;Sun|Ìràwọ̀ tó sun mọ́ ayé jù;Earth|Plánẹ́ẹ̀tì tí a ń gbé;Moon|Satẹlaiti àdánidá ilẹ̀ ayé;Mercury|Plánẹ́ẹ̀tì tó sun mọ́ Oòrùn jù;Jupiter|Plánẹ́ẹ̀tì tó tóbi jù;Mars|Plánẹ́ẹ̀tì pupa;Gravity|Agbára tó ń fa ohun sí ilẹ̀;Evaporation|Ìyípadà omi sí gaasi;Condensation|Ìyípadà gaasi sí omi;Freezing|Ìyípadà omi sí yìnyín;Melting|Ìyípadà solid sí liquid;Thermometer|Ohun èlò fún wiwọn temperature;Microscope|Ohun èlò fún rí ohun kékeré;Telescope|Ohun èlò fún wo ohun jíjìn;Magnet|Ohun tó ń fa irin kan mọ́ra;Solid|Ipo matter tó ní shape tirẹ̀;Liquid|Ipo matter tó gba shape àpò rẹ̀;Gas|Ipo matter tó tàn ká ààyè;Vertebrate|Ẹranko tó ní egungun ẹ̀yìn;Mammal|Ẹranko tó ń fún ọmọ rẹ̀ ní ọmú;Herbivore|Ẹranko tó ń jẹ ewéko;Carnivore|Ẹranko tó ń jẹ ẹran;Omnivore|Ẹranko tó ń jẹ ewéko àti ẹran;Habitat|Ibi tí ohun alààyè ń gbé;Cell|Ìpìlẹ̀ kékeré jù ti ohun alààyè;Atom|Ìpìlẹ̀ kékeré ti element;Force|Push or pull;Energy|Agbára láti ṣe iṣẹ́;Sound|Vibration tí etí lè gbọ́`,
Inventors:`Alexander Graham Bell|Telephone;Thomas Edison|Practical incandescent light bulb;Wright brothers|Powered aeroplane;Johannes Gutenberg|Movable-type printing press in Europe;Tim Berners-Lee|World Wide Web;James Watt|Improved steam engine;Samuel Morse|Morse code;Louis Braille|Braille reading system;Guglielmo Marconi|Radio communication development;Nikola Tesla|Alternating-current power system;Karl Benz|Early practical automobile;John Logie Baird|Early television demonstration;Charles Babbage|Analytical Engine concept;Ada Lovelace|Early published computer algorithm;Alexander Fleming|Discovery of penicillin;Edward Jenner|Smallpox vaccine development;Marie Curie|Pioneering research on radioactivity;Michael Faraday|Electromagnetic induction;Isaac Newton|Laws of motion and gravitation;Galileo Galilei|Astronomical use of the telescope;Grace Hopper|Compiler development pioneer;Hedy Lamarr|Frequency-hopping communication concept;Garrett Morgan|Three-position traffic signal patent`,
WorldKnowledge:`Nigeria|Abuja;Ghana|Accra;Kenya|Nairobi;Egypt|Cairo;South Africa|Pretoria;Ethiopia|Addis Ababa;Senegal|Dakar;Rwanda|Kigali;Tanzania|Dodoma;Uganda|Kampala;United Kingdom|London;France|Paris;Germany|Berlin;Italy|Rome;Spain|Madrid;Portugal|Lisbon;Ireland|Dublin;Belgium|Brussels;Netherlands|Amsterdam;Greece|Athens;United States|Washington, D.C.;Canada|Ottawa;Mexico|Mexico City;Brazil|Brasília;Argentina|Buenos Aires;Peru|Lima;Jamaica|Kingston;Cuba|Havana;China|Beijing;Japan|Tokyo;India|New Delhi;Pakistan|Islamabad;Saudi Arabia|Riyadh;United Arab Emirates|Abu Dhabi;Thailand|Bangkok;South Korea|Seoul;Indonesia|Jakarta;Australia|Canberra;New Zealand|Wellington;Turkey|Ankara;Norway|Oslo;Sweden|Stockholm;Denmark|Copenhagen;Finland|Helsinki;Switzerland|Bern`
};
function hash(text){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function opts(correct,pool,key){const result=[String(correct)],available=[...new Set(pool.map(String))].filter(x=>x!==String(correct));let p=hash(key)%available.length;while(result.length<4&&available.length){result.push(available.splice(p%available.length,1)[0]);p+=7}return result}
function add(id,category,difficulty,question,correct,pool,hint,explanation){bank.push({id,category,difficulty,question,answers:opts(correct,pool,id),correct:0,hint,explanation})}
const categoryNames={Language:"Èdè Yorùbá",Proverbs:"Òwe Yorùbá",YorubaHistory:"Ìtàn Yorùbá",YorubaKings:"Àwọn Ọba Yorùbá",Agriculture:"Iṣẹ́ Àgbẹ̀",NigeriaEducation:"Nàìjíríà àti Ilé Ẹ̀kọ́",Literature:"Ìwé àti Òǹkọ̀wé",Sports:"Eré Ìdárayá",Science:"Ìmọ̀ Sáyẹ́ǹsì",Inventors:"Àwọn Olùdásílẹ̀",WorldKnowledge:"Ìmọ̀ Ayé"};
Object.entries(datasets).forEach(([category,text])=>{const facts=text.split(";").map(row=>row.split("|")),terms=facts.map(x=>x[0]),values=facts.map(x=>x[1]),label=categoryNames[category];facts.forEach(([term,value],i)=>{const d=levels[i%3],note=`${term} — ${value}.`;add(`${category}-${i}-a`,category,d,`Nínú ẹ̀ka ${label}, kí ni ìdáhùn tó bá “${term}” mu jù?`,value,values,"Yan ìtumọ̀ tàbí àlàyé tó pé.",note);add(`${category}-${i}-b`,category,d,`Èwo ni ó bá “${value}” mu?`,term,terms,"Wo àwọn aṣàyàn náà dáadáa.",note);add(`${category}-${i}-c`,category,d,`Nínú ẹ̀ka ${label}, yan àlàyé tó tọ́ fún “${term}”.`,value,values,"Ìdáhùn kan ṣoṣo ló pé.",note)})});
function addMath(id,question,answer,step,difficulty,explanation){const pool=[answer,answer+step,Math.max(0,answer-step),answer+step*2,answer+step*3];add(id,"Math",difficulty,question,answer,pool,"Ṣe ìṣirò náà díẹ̀díẹ̀.",explanation)}
for(let n=1;n<=100;n++){const b=n%19+2,f=n%11+2;addMath(`math-add-${n}`,`Kí ni ${n} + ${b}?`,n+b,1,levels[n%3],`${n} + ${b} = ${n+b}.`);addMath(`math-sub-${n}`,`Kí ni ${n+b} − ${b}?`,n,1,levels[(n+1)%3],`${n+b} − ${b} = ${n}.`);addMath(`math-mul-${n}`,`Kí ni ${n} × ${f}?`,n*f,f,levels[(n+2)%3],`${n} × ${f} = ${n*f}.`);addMath(`math-div-${n}`,`Kí ni ${n*f} ÷ ${f}?`,n,1,levels[n%3],`${n*f} ÷ ${f} = ${n}.`)}
window.YORUBA_QUESTIONS=bank;
})();
