'use strict';
const articles=window.ENCYCLo;
const $=id=>document.getElementById(id);
const normal=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const escapeHTML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=k=>{try{return localStorage.getItem(k)}catch{return null}};
const put=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
let bookmarks;try{bookmarks=new Set(JSON.parse(get('encyclo-saved')||'[]').filter(id=>articles.some(a=>a.id===id)))}catch{bookmarks=new Set()}
let category='All subjects',savedOnly=false,lastFocus=null;
const categories=['All subjects',...new Set(articles.map(a=>a.category))];
const card=a=>`<article class="card"><div class="card-art" aria-hidden="true"><span class="symbol">${escapeHTML(a.symbol)}</span><span class="tag">${escapeHTML(a.category.toUpperCase())}</span></div><div class="card-body"><h3><a href="#article=${a.id}" data-read="${a.id}">${escapeHTML(a.title)}</a></h3><p>${escapeHTML(a.summary)}</p><div class="card-bottom"><a href="#article=${a.id}" data-read="${a.id}">Read introduction ↗</a><button class="bookmark" data-save="${a.id}" aria-label="${bookmarks.has(a.id)?'Unsave':'Save'} ${escapeHTML(a.title)}" aria-pressed="${bookmarks.has(a.id)}">${bookmarks.has(a.id)?'Saved':'Save'}</button></div></div></article>`;
function render(){const words=normal($('query').value.trim()).split(/\s+/).filter(Boolean);const matches=articles.filter(a=>(category==='All subjects'||a.category===category)&&(!savedOnly||bookmarks.has(a.id))&&words.every(w=>normal([a.title,a.category,a.tags,a.summary,...a.paragraphs].join(' ')).includes(w)));$('cards').innerHTML=matches.length?matches.map(card).join(''):'<div class="empty"><h3>No articles match yet.</h3><p>Try a broader word or reset the filters. This is a growing introductory collection.</p><a href="mailto:obanimistudio@gmail.com?subject=ObanimiEncyclo%20topic%20suggestion">Suggest a topic ↗</a></div>';$('status').textContent=`${matches.length} ${matches.length===1?'article':'articles'}${words.length?' matching your search':''}${savedOnly?' in your saved collection':''}`;$('saved-count').textContent=bookmarks.size;$('saved').setAttribute('aria-pressed',savedOnly);$('filters').innerHTML=categories.map(c=>`<button data-category="${escapeHTML(c)}" aria-pressed="${c===category}">${escapeHTML(c)}</button>`).join('')}
function save(id){if(bookmarks.has(id))bookmarks.delete(id);else bookmarks.add(id);put('encyclo-saved',JSON.stringify([...bookmarks]));render();const b=document.querySelector(`[data-save="${id}"]`);if(b)b.focus();if($('reader').open){const rb=$('article-save');rb.textContent=bookmarks.has(id)?'Saved on this device':'Save article';rb.setAttribute('aria-pressed',bookmarks.has(id))}}
function openArticle(id){const a=articles.find(a=>a.id===id);if(!a)return;lastFocus=document.activeElement;$('article').innerHTML=`<p class="eyebrow">${escapeHTML(a.category)}</p><h2 id="article-title">${escapeHTML(a.title)}</h2><p class="meta">Introductory guide · Sources checked 2 October 2026 · AI-assisted; not expert-reviewed</p>${a.paragraphs.map(p=>`<p>${escapeHTML(p)}</p>`).join('')}<h3>Sources &amp; further reading</h3><ul>${a.sources.map(([label,url])=>`<li><a href="${escapeHTML(url)}" target="_blank" rel="noopener noreferrer">${escapeHTML(label)} ↗</a></li>`).join('')}</ul><div class="actions"><button id="article-save" aria-pressed="${bookmarks.has(id)}">${bookmarks.has(id)?'Saved on this device':'Save article'}</button><button id="share">Copy article link</button></div><p id="share-status" class="meta" role="status"></p><p><a class="correction" href="mailto:obanimistudio@gmail.com?subject=${encodeURIComponent('ObanimiEncyclo correction: '+a.title)}">Report an error or suggest an improvement ↗</a></p>`;if(!$('reader').open)$('reader').showModal();$('reader').scrollTop=0;$('article-save').onclick=()=>save(id);$('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href);$('share-status').textContent='Link copied. You can paste it into a message.'}catch{$('share-status').textContent='Copy this link from your address bar: '+location.href}}}
function route(){const id=new URLSearchParams(location.hash.slice(1)).get('article');if(id)openArticle(id);else if($('reader').open)$('reader').close()}
function reset(){category='All subjects';savedOnly=false;$('query').value='';render()}
document.addEventListener('click',e=>{const read=e.target.closest('[data-read]');if(read){e.preventDefault();if(location.hash===`#article=${read.dataset.read}`)openArticle(read.dataset.read);else location.hash=`article=${read.dataset.read}`}const b=e.target.closest('[data-save]');if(b)save(b.dataset.save);const c=e.target.closest('[data-category]');if(c){category=c.dataset.category;render();[...$('filters').children].find(b=>b.dataset.category===category)?.focus()}const q=e.target.closest('[data-query]');if(q){reset();$('query').value=q.dataset.query;render();$('explore').scrollIntoView()}});
$('query').addEventListener('input',render);$('search').onsubmit=e=>{e.preventDefault();render();$('explore').scrollIntoView()};$('saved').onclick=()=>{savedOnly=!savedOnly;render()};$('reset').onclick=reset;
$('close').onclick=()=>{$('reader').close()};$('reader').addEventListener('close',()=>{if(location.hash.startsWith('#article='))history.replaceState(null,'',location.pathname+location.search);lastFocus?.focus()});window.addEventListener('hashchange',route);
function theme(dark){document.body.classList.toggle('dark',dark);$('theme').textContent=dark?'Light mode':'Dark mode';$('theme').setAttribute('aria-label',dark?'Switch to light colour theme':'Switch to dark colour theme')}
theme(get('encyclo-theme')==='dark');$('theme').onclick=()=>{const dark=!document.body.classList.contains('dark');theme(dark);put('encyclo-theme',dark?'dark':'light')};$('year').textContent=new Date().getFullYear();$('total').textContent=articles.length;render();route();
